# Generated by Django 5.2.7 on 2025-10-15 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas_medicas_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='paciente',
            name='edad',
            field=models.IntegerField(default=30),
        ),
    ]
