# Generated by Django 5.2.7 on 2025-10-15 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas_medicas_api', '0002_paciente_edad'),
    ]

    operations = [
        migrations.RenameField(
            model_name='consultamedica',
            old_name='fecha',
            new_name='fecha_consulta',
        ),
        migrations.RenameField(
            model_name='medicamento',
            old_name='presentacion',
            new_name='laboratorio',
        ),
        migrations.RemoveField(
            model_name='consultamedica',
            name='receta',
        ),
        migrations.RemoveField(
            model_name='paciente',
            name='edad',
        ),
        migrations.RemoveField(
            model_name='recetamedica',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='recetamedica',
            name='medico',
        ),
        migrations.RemoveField(
            model_name='recetamedica',
            name='paciente',
        ),
        migrations.AddField(
            model_name='consultamedica',
            name='estado',
            field=models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('FINALIZADA', 'Finalizada'), ('CANCELADA', 'Cancelada')], default='PENDIENTE', max_length=20),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='precio_unitario',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='medicamento',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='medico',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='medico',
            name='rut',
            field=models.CharField(default='00000000-0', max_length=12),
        ),
        migrations.AddField(
            model_name='paciente',
            name='activo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='paciente',
            name='direccion',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='recetamedica',
            name='consulta',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='citas_medicas_api.consultamedica'),
        ),
        migrations.AddField(
            model_name='recetamedicamento',
            name='duracion',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.CreateModel(
            name='SeguroMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('poliza', models.CharField(max_length=50)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguros', to='citas_medicas_api.paciente')),
            ],
        ),
        migrations.DeleteModel(
            name='HistorialMedico',
        ),
    ]
