# Generated by Django 5.2.7 on 2025-10-16 00:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('citas_medicas_api', '0003_rename_fecha_consultamedica_fecha_consulta_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='HistorialMedico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('consulta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to='citas_medicas_api.consultamedica')),
                ('medico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to='citas_medicas_api.medico')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historiales', to='citas_medicas_api.paciente')),
            ],
            options={
                'verbose_name': 'Historial Médico',
                'verbose_name_plural': 'Historiales Médicos',
            },
        ),
    ]
